export const DEFAULT_SETTINGS = {
  OPENCODE_MEM_MODEL: 'claude-sonnet-4-6',
  OPENCODE_MEM_CONTEXT_OBSERVATIONS: '50',
  OPENCODE_MEM_WORKER_PORT: '37700',
  OPENCODE_MEM_WORKER_HOST: '127.0.0.1',

  OPENCODE_MEM_PROVIDER: 'claude',
  OPENCODE_MEM_GEMINI_API_KEY: '',
  OPENCODE_MEM_GEMINI_MODEL: 'gemini-2.5-flash-lite',
  OPENCODE_MEM_OPENROUTER_API_KEY: '',
  OPENCODE_MEM_OPENROUTER_MODEL: 'xiaomi/mimo-v2-flash:free',
  OPENCODE_MEM_OPENROUTER_SITE_URL: '',
  OPENCODE_MEM_OPENROUTER_APP_NAME: 'opencode-mem',
  OPENCODE_MEM_GEMINI_RATE_LIMITING_ENABLED: 'true',

  OPENCODE_MEM_CONTEXT_SHOW_READ_TOKENS: 'false',
  OPENCODE_MEM_CONTEXT_SHOW_WORK_TOKENS: 'false',
  OPENCODE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: 'false',
  OPENCODE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  OPENCODE_MEM_CONTEXT_FULL_COUNT: '0',
  OPENCODE_MEM_CONTEXT_FULL_FIELD: 'narrative',
  OPENCODE_MEM_CONTEXT_SESSION_COUNT: '10',

  OPENCODE_MEM_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  OPENCODE_MEM_CONTEXT_SHOW_LAST_MESSAGE: 'false',
} as const;
